version: '2'
services:
    employeemonitor-app:
        image: employeemonitor
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://employeemonitor-postgresql:5432/EmployeeMonitor
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    employeemonitor-postgresql:
        extends:
            file: postgresql.yml
            service: employeemonitor-postgresql
